[package]
name = "dm-archive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
blake2 = "0.10"
byteorder = "1.4"
clap = { version = "3.1.0", features = ["cargo"] }
crossbeam = "0.8.1"
flate2 = "1.0"
generic-array = "0.14"
nom = "7.1"
num_enum = "0.5.6"
rand = "0.8"
rand_chacha = "0.3"
serde = "1.0.136"
serde_derive = "1.0.136"
# thinp = { git = "https://github.com/jthornber/thin-provisioning-tools.git", branch = "main" }
thinp = { path = "../thinp-for-dm-archive/" }
threadpool = "1.0"
toml = "0.5.8"
